apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  selector:
    matchLabels:
      run: backend-user
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-user
    spec:
      containers:
      - name: backend-user
        image: docker.io/omotayoishola/udagram-api-user:v1
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: env-config
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m


---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: backend-user
  name: user
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    run: backend-user
